services:
      
  api-gateway:
    image: asankamadhawa/mantraiq-sankhya-naming-server:latest   
    ports:
      - "8765:8765"
    networks:
      - mantra_iq-bank-network
    depends_on:
      - naming-server   
    extra_hosts:
      - "host.docker.internal:host-gateway" 
      
  transaction-service:
    image: asankamadhawa/mantraiq-sankhya-transaction-service:latest    
    ports:
      - "8100:8100"
    networks:
      - mantra_iq-bank-network
    depends_on:
      - naming-server
    extra_hosts:
      - "host.docker.internal:host-gateway" 
    # mem_limit: 1024m  # Increased to 1GB
    environment:
      - JAVA_TOOL_OPTIONS=-Djava.awt.headless=true -XX:MaxMetaspaceSize=150M -XX:ReservedCodeCacheSize=100M -Xmx500M -Xss512k -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions
      - JAVA_OPTS=-Djava.awt.headless=true
      - SPRING_JAVA_OPTS=-Djava.awt.headless=true
      - BPL_JVM_HEAD_ROOM=10
      - BPL_JVM_LOADED_CLASS_COUNT=35
      - BPL_JVM_THREAD_COUNT=
      - FONTCONFIG_PATH=/etc/fonts
      - FONTCONFIG_FILE=/etc/fonts/fonts.conf
      - _JAVA_OPTIONS=-Djava.awt.headless=true -Dnet.sf.jasperreports.awt.ignore.missing.font=true
    
      
  loan-service:
    image: asankamadhawa/mantraiq-sankhya-loan-service:latest 
    ports:
      - "8200:8200"
    networks:
      - mantra_iq-bank-network
    depends_on:
      - naming-server
    extra_hosts:
      - "host.docker.internal:host-gateway" 
            
  customer-service:
    image: asankamadhawa/mantraiq-sankhya-customer-service:latest    
    ports:
      - "8300:8300"
    networks:
      - mantra_iq-bank-network
    depends_on:
      - naming-server
    extra_hosts:
      - "host.docker.internal:host-gateway" 
            
  user-service:
    image: asankamadhawa/mantraiq-sankhya-user-service:latest    
    ports:
      - "8000:8000"
    networks:
      - mantra_iq-bank-network
    depends_on:
      - naming-server
    extra_hosts:
      - "host.docker.internal:host-gateway" 
      
  naming-server:
    image: asankamadhawa/mantraiq-sankhya-naming-server:latest   
    ports:
      - "8761:8761"
    networks:
      - mantra_iq-bank-network
    extra_hosts:
      - "host.docker.internal:host-gateway" 
                  
  zipkin-server:
    image: openzipkin/zipkin:2.23
    mem_limit: 300m
    ports:
      - "9412:9412"
    networks:
      - mantra_iq-bank-network
    restart: always #Restart if there is a problem starting up
    extra_hosts:
      - "host.docker.internal:host-gateway"   

networks:
  mantra_iq-bank-network:

volumes:
  mysql_data:
